import type { Meta, StoryObj } from '@storybook/react';
import { TableBlock, TableRowData, FilterGroup } from '@/blocks/data-block/TableBlock';
import { CheckIcon, CloseIcon } from '@heroui/shared-icons';
import { fn } from '@storybook/test';

const meta: Meta<typeof TableBlock> = {
  title: 'Blocks/Data/TableBlock',
  component: TableBlock,
  tags: ['autodocs'],
  argTypes: {
    columns: { control: 'object' },
    data: { control: 'object' },
    // striped, bordered, compact removed as they should be inferred or are not direct props for argTypes control
  },
  args: {
    onSelectionChange: fn(),
    // onSort removed from meta.args, will be defined in individual stories
  },
};

export default meta;
type Story = StoryObj<typeof TableBlock>;

// Define filterGroups
const exampleFilterGroups: FilterGroup[] = [
  {
    id: 'status',
    name: 'Status',
    options: [
      { label: 'Active', value: 'active', filterFn: (row) => row.status === 'Active' },
      { label: 'Inactive', value: 'inactive', filterFn: (row) => row.status === 'Inactive' },
    ],
  },
  {
    id: 'decade',
    name: 'Age Decade',
    options: [
      { label: '20-29', value: '20s', filterFn: (row) => typeof row.age === 'number' && row.age >= 20 && row.age <= 29 },
      { label: '30-39', value: '30s', filterFn: (row) => typeof row.age === 'number' && row.age >= 30 && row.age <= 39 },
      { label: '40-49', value: '40s', filterFn: (row) => typeof row.age === 'number' && row.age >= 40 && row.age <= 49 },
      { label: '50-59', value: '50s', filterFn: (row) => typeof row.age === 'number' && row.age >= 50 && row.age <= 59 },
      { label: '60+', value: '60plus', filterFn: (row) => typeof row.age === 'number' && row.age >= 60 },
    ],
  },
];

export const Basic: Story = {
  args: {
    id: 'table-block-example',
    columns: [
      { header: 'Name', accessor: 'name' },
      { header: 'Age', accessor: 'age' },
      { header: 'Status', accessor: 'status' },
    ],
    data: [
      { name: 'John Doe', age: 28, status: 'Active' },
      { name: 'Caleb Stone', age: 34, status: 'Inactive' },
      { name: 'Bob Johnson', age: 45, status: 'Active' },
    ],
    onSelectionChange: fn(),
    // onSort removed as it's not essential for this basic story and causing TS issues
  },
};

export const WithTitle: Story = {
  args: {
    id: 'table-block-title-example',
    columns: [
      { header: 'Name', accessor: 'name' },
      { header: 'Age', accessor: 'age' },
      { header: 'Status', accessor: 'status' },
    ],
    data: [
      { name: 'John Doe', age: 28, status: 'Active' },
      { name: 'Caleb Stone', age: 34, status: 'Inactive' },
      { name: 'Bob Johnson', age: 45, status: 'Active' },
    ],
    title: 'List of Users',
    onSelectionChange: fn(),
    // onSort removed as it's not essential for this story and causing TS issues
  },
};

export const Customized: Story = {
  args: {
    id: 'table-block-customized-example',
    columns: [
      { header: 'Name', accessor: 'name', sortable: true },
      { header: 'Age', accessor: 'age', sortable: true },
      { header: 'Status', accessor: 'status', cell: (info: TableRowData) =>
        info.status === 'Active'
          ? <CheckIcon style={{ color: 'green' }} />
          : <CloseIcon style={{ color: 'red' }} />},
    ],
    data: [
      { name: 'John Doe', age: 28, status: 'Active' },
      { name: 'Bob Johnson', age: 45, status: 'Active' },
      { name: 'Caleb Stone', age: 34, status: 'Inactive' },
      { name: 'Alice Smith', age: 31, status: 'Inactive' },
      { name: 'Ethan Brown', age: 39, status: 'Active' },
      { name: 'Olivia Green', age: 27, status: 'Inactive' },
      { name: 'Mason Lee', age: 52, status: 'Active' },
      { name: 'Sophia Harris', age: 41, status: 'Inactive' },
      { name: 'Liam Walker', age: 36, status: 'Active' },
      { name: 'Ava Hall', age: 22, status: 'Inactive' },
      { name: 'Noah Allen', age: 60, status: 'Active' },
      { name: 'Isabella Young', age: 29, status: 'Inactive' },
      { name: 'Lucas King', age: 47, status: 'Active' },
      { name: 'Mia Wright', age: 33, status: 'Inactive' },
      { name: 'Benjamin Scott', age: 54, status: 'Active' },
      { name: 'Charlotte Adams', age: 26, status: 'Inactive' },
      { name: 'Elijah Baker', age: 38, status: 'Active' },
      { name: 'Amelia Nelson', age: 42, status: 'Inactive' },
      { name: 'James Carter', age: 49, status: 'Active' },
      { name: 'Harper Mitchell', age: 25, status: 'Inactive' },
      { name: 'William Perez', age: 61, status: 'Active' },
      { name: 'Evelyn Roberts', age: 32, status: 'Inactive' },
      { name: 'Henry Turner', age: 57, status: 'Active' },
      { name: 'Abigail Phillips', age: 24, status: 'Inactive' },
      { name: 'Alexander Campbell', age: 40, status: 'Active' },
      { name: 'Emily Parker', age: 35, status: 'Inactive' },
      { name: 'Daniel Evans', age: 44, status: 'Active' },
      { name: 'Elizabeth Edwards', age: 30, status: 'Inactive' },
      { name: 'Matthew Collins', age: 50, status: 'Active' },
      { name: 'Ella Stewart', age: 23, status: 'Inactive' },
      { name: 'Jackson Morris', age: 62, status: 'Active' },
      { name: 'Scarlett Rogers', age: 28, status: 'Inactive' },
      { name: 'Sebastian Reed', age: 53, status: 'Active' },
      { name: 'Grace Cook', age: 37, status: 'Inactive' },
      { name: 'David Morgan', age: 59, status: 'Active' },
      { name: 'Chloe Bell', age: 21, status: 'Inactive' },
      { name: 'Carter Murphy', age: 48, status: 'Active' },
      { name: 'Penelope Bailey', age: 43, status: 'Inactive' },
      { name: 'Wyatt Rivera', age: 55, status: 'Active' },
      { name: 'Layla Cooper', age: 27, status: 'Inactive' },
      { name: 'Gabriel Richardson', age: 46, status: 'Active' },
      { name: 'Riley Cox', age: 34, status: 'Inactive' },
      { name: 'Julian Howard', age: 63, status: 'Active' },
      { name: 'Nora Ward', age: 40, status: 'Inactive' },
      { name: 'Levi Torres', age: 56, status: 'Active' },
      { name: 'Zoey Peterson', age: 23, status: 'Inactive' },
      { name: 'Jack Gray', age: 37, status: 'Active' },
      { name: 'Lillian Ramirez', age: 32, status: 'Inactive' },
      { name: 'Owen James', age: 42, status: 'Active' },
      { name: 'Addison Watson', age: 26, status: 'Inactive' },
      { name: 'Samuel Brooks', age: 51, status: 'Active' },
      { name: 'Hannah Kelly', age: 29, status: 'Inactive' },
      { name: 'Luke Sanders', age: 44, status: 'Active' },
      { name: 'Avery Price', age: 36, status: 'Inactive' },
      { name: 'Lincoln Bennett', age: 58, status: 'Active' },
      { name: 'Stella Wood', age: 24, status: 'Inactive' },
      { name: 'Isaac Barnes', age: 41, status: 'Active' },
      { name: 'Natalie Ross', age: 35, status: 'Inactive' },
      { name: 'Jayden Henderson', age: 60, status: 'Active' },
      { name: 'Violet Coleman', age: 27, status: 'Inactive' },
      { name: 'Grayson Jenkins', age: 47, status: 'Active' },
      { name: 'Aurora Perry', age: 31, status: 'Inactive' },
      { name: 'Dylan Powell', age: 53, status: 'Active' },
      { name: 'Savannah Long', age: 22, status: 'Inactive' },
      { name: 'Anthony Patterson', age: 39, status: 'Active' },
      { name: 'Brooklyn Hughes', age: 34, status: 'Inactive' },
      { name: 'Jaxon Flores', age: 45, status: 'Active' },
      { name: 'Leah Washington', age: 28, status: 'Inactive' },
      { name: 'Joshua Butler', age: 55, status: 'Active' },
      { name: 'Hazel Simmons', age: 25, status: 'Inactive' },
      { name: 'Christopher Foster', age: 41, status: 'Active' },
      { name: 'Ellie Bryant', age: 33, status: 'Inactive' },
      { name: 'Andrew Alexander', age: 52, status: 'Active' },
      { name: 'Paisley Russell', age: 30, status: 'Inactive' },
      { name: 'Josiah Griffin', age: 38, status: 'Active' },
      { name: 'Audrey Diaz', age: 26, status: 'Inactive' },
      { name: 'Hudson Hayes', age: 49, status: 'Active' },
      { name: 'Skylar Myers', age: 31, status: 'Inactive' },
      { name: 'Adam Ford', age: 43, status: 'Active' },
      { name: 'Lucy Hamilton', age: 36, status: 'Inactive' },
      { name: 'Nathan Graham', age: 54, status: 'Active' },
      { name: 'Bella Sullivan', age: 29, status: 'Inactive' },
      { name: 'Christian Wallace', age: 48, status: 'Active' },
      { name: 'Samantha West', age: 23, status: 'Inactive' },
      { name: 'Jonathan Cole', age: 50, status: 'Active' },
      { name: 'Madelyn Jordan', age: 28, status: 'Inactive' },
      { name: 'Hunter Chapman', age: 57, status: 'Active' },
      { name: 'Aubrey Montgomery', age: 25, status: 'Inactive' },
      { name: 'Connor Hunt', age: 44, status: 'Active' },
      { name: 'Brooklyn Bishop', age: 35, status: 'Inactive' },
      { name: 'Aaron Mason', age: 59, status: 'Active' },
      { name: 'Kennedy Lane', age: 22, status: 'Inactive' },
      { name: 'Eli Knight', age: 46, status: 'Active' },
      { name: 'Caroline Craig', age: 32, status: 'Inactive' },
      { name: 'Jeremiah Bishop', age: 56, status: 'Active' },
      { name: 'Genesis Cross', age: 27, status: 'Inactive' },
      { name: 'Easton Stone', age: 38, status: 'Active' },
      { name: 'Sadie Lambert', age: 24, status: 'Inactive' },
      { name: 'Colton Nichols', age: 42, status: 'Active' },
      { name: 'Allison Watts', age: 33, status: 'Inactive' },
      { name: 'Robert Lowe', age: 51, status: 'Active' },
      { name: 'Hailey Dean', age: 26, status: 'Inactive' },
      { name: 'Angel Martinez', age: 37, status: 'Active' },
      { name: 'Aaliyah Bishop', age: 29, status: 'Inactive' },
      { name: 'Thomas Garrett', age: 58, status: 'Active' },
      { name: 'Gabriella Brewer', age: 21, status: 'Inactive' },
      { name: 'Charles Holland', age: 40, status: 'Active' },
      { name: 'Naomi Banks', age: 34, status: 'Inactive' },
      { name: 'Josie Fleming', age: 47, status: 'Active' },
      { name: 'Peyton Shaw', age: 31, status: 'Inactive' },
      { name: 'Brayden Doyle', age: 53, status: 'Active' },
      { name: 'Ruby Barber', age: 28, status: 'Inactive' },
      { name: 'Nicholas Paul', age: 39, status: 'Active' },
      { name: 'Anna Maxwell', age: 22, status: 'Inactive' },
      { name: 'Bentley Newman', age: 46, status: 'Active' },
      { name: 'Serenity Watts', age: 30, status: 'Inactive' },
      { name: 'Jace Davidson', age: 55, status: 'Active' },
      { name: 'Autumn Brewer', age: 25, status: 'Inactive' },
      { name: 'Dominic Bishop', age: 43, status: 'Active' },
      { name: 'Quinn Parsons', age: 37, status: 'Inactive' },
      { name: 'Parker Lane', age: 50, status: 'Active' },
      { name: 'Melanie Poole', age: 23, status: 'Inactive' },
      { name: 'Miles Franklin', age: 41, status: 'Active' },
      { name: 'Faith Reese', age: 35, status: 'Inactive' },
      { name: 'Jason Doyle', age: 49, status: 'Active' },
      { name: 'Ariana Norton', age: 27, status: 'Inactive' },
      { name: 'Brody Griffin', age: 62, status: 'Active' },
      { name: 'Eva Schwartz', age: 33, status: 'Inactive' },
      { name: 'Vincent Lawrence', age: 45, status: 'Active' },
      { name: 'Mila Harmon', age: 28, status: 'Inactive' },
      { name: 'Everett Barker', age: 57, status: 'Active' },
      { name: 'Kinsley Ramsey', age: 24, status: 'Inactive' },
      { name: 'Micah McBride', age: 36, status: 'Active' },
      { name: 'Jasmine Carter', age: 31, status: 'Inactive' },
      { name: 'Kayden Pope', age: 53, status: 'Active' },
      { name: 'Morgan Gilbert', age: 29, status: 'Inactive' },
      { name: 'Bryson Drake', age: 48, status: 'Active' },
      { name: 'Valentina Francis', age: 22, status: 'Inactive' },
      { name: 'Weston Sherman', age: 44, status: 'Active' },
      { name: 'Delilah Ballard', age: 25, status: 'Inactive' },
      { name: 'Ayden McCoy', age: 54, status: 'Active' },
      { name: 'Jade Zimmerman', age: 30, status: 'Inactive' },
      { name: 'Diego Brady', age: 41, status: 'Active' },
      { name: 'Mackenzie Kirby', age: 27, status: 'Inactive' },
      { name: 'Carlos Velez', age: 59, status: 'Active' },
      { name: 'Trinity McKinney', age: 24, status: 'Inactive' },
      { name: 'Zachary Pace', age: 38, status: 'Active' },
      { name: 'Isabelle Hodge', age: 35, status: 'Inactive' },
      { name: 'Maximus McGuire', age: 47, status: 'Active' },
      { name: 'Molly Dunlap', age: 21, status: 'Inactive' },
      { name: 'Kingston Pratt', age: 42, status: 'Active' },
      { name: 'Jocelyn Dyer', age: 32, status: 'Inactive' },
      { name: 'Kaiden Cline', age: 56, status: 'Active' },
      { name: 'Alexis Short', age: 26, status: 'Inactive' },
      { name: 'Asher Walls', age: 43, status: 'Active' },
      { name: 'Madeline Mays', age: 23, status: 'Inactive' },
      { name: 'Camden McCall', age: 52, status: 'Active' },
      { name: 'Piper Morrow', age: 28, status: 'Inactive' },
      { name: 'Bentley Hodge', age: 39, status: 'Active' },
      { name: 'Lydia Guerra', age: 31, status: 'Inactive' },
      { name: 'Xavier Gentry', age: 58, status: 'Active' },
      { name: 'Juliana McDaniel', age: 25, status: 'Inactive' },
      { name: 'Everly Dorsey', age: 36, status: 'Active' },
      { name: 'Jaxson McIntyre', age: 34, status: 'Inactive' },
      { name: 'Mateo Booth', age: 60, status: 'Active' },
      { name: 'Arianna Duffy', age: 27, status: 'Inactive' },
      { name: 'Ezra McLeod', age: 49, status: 'Active' },
      { name: 'Ayla Hensley', age: 22, status: 'Inactive' }
    ],
    selectable: true,
    actions: [
      {
        label: 'Log Selected',
        handler: (rows: TableRowData[]) => console.log('Selected rows', rows),
      },
      {
        label: 'Alert Count',
        handler: (rows: TableRowData[]) => alert(`${rows.length} selected`),
        disabled: rows => rows.length === 0,
      },
    ],
    onSelectionChange: fn(),
    onSort: fn(), // Corrected from onSortChange
    // Add the filterGroups prop
    filterGroups: exampleFilterGroups,
  } as Partial<import('@/blocks/data-block/TableBlock').TableBlockProps>,
};
